---

- yum:
    state: present
    name: "{{item}}"
  with_items:
    - curl
    - gcc
    - gcc-c++
    - openssl-devel
    - readline-devel

- shell: "/home/isucon/xbuild/ruby-install -f 2.4.2 /home/isucon/local/ruby"
  args:
    creates: /home/isucon/local/ruby/bin/bundle
  become_user: isucon

- shell: /home/isucon/local/ruby/bin/bundle install
  args:
    chdir: /home/isucon/isubata/webapp/ruby
  become_user: isucon

- copy:
    src: /home/isucon/isubata/files/app/isubata.ruby.service
    dest: /etc/systemd/system/
    remote_src: yes
  notify: daemon-reload

- set_fact:
    app_service: ruby
